/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EditMessageRequest } from '../../models/edit-message-request';
import { MessageResponse } from '../../models/message-response';

export interface EditMessage$Params {
  'conversation-id': string;
  'message-id': number;
      body: EditMessageRequest
}

export function editMessage(http: HttpClient, rootUrl: string, params: EditMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageResponse>> {
  const rb = new RequestBuilder(rootUrl, editMessage.PATH, 'patch');
  if (params) {
    rb.path('conversation-id', params['conversation-id'], {});
    rb.path('message-id', params['message-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageResponse>;
    })
  );
}

editMessage.PATH = '/api/v1/conversations/{conversation-id}/messages/{message-id}';
