/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessagePageResponse } from '../../models/message-page-response';

export interface GetMessages$Params {
  'conversation-id': string;
  before?: number;
  limit?: number;
}

export function getMessages(http: HttpClient, rootUrl: string, params: GetMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<MessagePageResponse>> {
  const rb = new RequestBuilder(rootUrl, getMessages.PATH, 'get');
  if (params) {
    rb.path('conversation-id', params['conversation-id'], {});
    rb.query('before', params.before, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessagePageResponse>;
    })
  );
}

getMessages.PATH = '/api/v1/conversations/{conversation-id}/messages';
