/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ConversationResponse } from '../models/conversation-response';
import { createConversation } from '../fn/conversation/create-conversation';
import { CreateConversation$Params } from '../fn/conversation/create-conversation';
import { getConversations } from '../fn/conversation/get-conversations';
import { GetConversations$Params } from '../fn/conversation/get-conversations';
import { StringResponse } from '../models/string-response';

@Injectable({ providedIn: 'root' })
export class ConversationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getConversations()` */
  static readonly GetConversationsPath = '/api/v1/conversations';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getConversations()` instead.
   *
   * This method doesn't expect any request body.
   */
  getConversations$Response(params?: GetConversations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConversationResponse>>> {
    return getConversations(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getConversations$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getConversations(params?: GetConversations$Params, context?: HttpContext): Observable<Array<ConversationResponse>> {
    return this.getConversations$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ConversationResponse>>): Array<ConversationResponse> => r.body)
    );
  }

  /** Path part for operation `createConversation()` */
  static readonly CreateConversationPath = '/api/v1/conversations';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createConversation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createConversation$Response(params: CreateConversation$Params, context?: HttpContext): Observable<StrictHttpResponse<StringResponse>> {
    return createConversation(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createConversation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createConversation(params: CreateConversation$Params, context?: HttpContext): Observable<StringResponse> {
    return this.createConversation$Response(params, context).pipe(
      map((r: StrictHttpResponse<StringResponse>): StringResponse => r.body)
    );
  }

}
