/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deleteMessage } from '../fn/message/delete-message';
import { DeleteMessage$Params } from '../fn/message/delete-message';
import { editMessage } from '../fn/message/edit-message';
import { EditMessage$Params } from '../fn/message/edit-message';
import { getMessages } from '../fn/message/get-messages';
import { GetMessages$Params } from '../fn/message/get-messages';
import { markMessagesAsRead } from '../fn/message/mark-messages-as-read';
import { MarkMessagesAsRead$Params } from '../fn/message/mark-messages-as-read';
import { MessagePageResponse } from '../models/message-page-response';
import { MessageResponse } from '../models/message-response';
import { sendMessage } from '../fn/message/send-message';
import { SendMessage$Params } from '../fn/message/send-message';
import { uploadAttachment } from '../fn/message/upload-attachment';
import { UploadAttachment$Params } from '../fn/message/upload-attachment';

@Injectable({ providedIn: 'root' })
export class MessageService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getMessages()` */
  static readonly GetMessagesPath = '/api/v1/conversations/{conversation-id}/messages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMessages()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMessages$Response(params: GetMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<MessagePageResponse>> {
    return getMessages(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMessages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMessages(params: GetMessages$Params, context?: HttpContext): Observable<MessagePageResponse> {
    return this.getMessages$Response(params, context).pipe(
      map((r: StrictHttpResponse<MessagePageResponse>): MessagePageResponse => r.body)
    );
  }

  /** Path part for operation `sendMessage()` */
  static readonly SendMessagePath = '/api/v1/conversations/{conversation-id}/messages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendMessage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendMessage$Response(params: SendMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageResponse>> {
    return sendMessage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendMessage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendMessage(params: SendMessage$Params, context?: HttpContext): Observable<MessageResponse> {
    return this.sendMessage$Response(params, context).pipe(
      map((r: StrictHttpResponse<MessageResponse>): MessageResponse => r.body)
    );
  }

  /** Path part for operation `uploadAttachment()` */
  static readonly UploadAttachmentPath = '/api/v1/conversations/{conversation-id}/messages/attachments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadAttachment()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadAttachment$Response(params: UploadAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageResponse>> {
    return uploadAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadAttachment$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadAttachment(params: UploadAttachment$Params, context?: HttpContext): Observable<MessageResponse> {
    return this.uploadAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<MessageResponse>): MessageResponse => r.body)
    );
  }

  /** Path part for operation `markMessagesAsRead()` */
  static readonly MarkMessagesAsReadPath = '/api/v1/conversations/{conversation-id}/read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markMessagesAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  markMessagesAsRead$Response(params: MarkMessagesAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return markMessagesAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markMessagesAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  markMessagesAsRead(params: MarkMessagesAsRead$Params, context?: HttpContext): Observable<void> {
    return this.markMessagesAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteMessage()` */
  static readonly DeleteMessagePath = '/api/v1/conversations/{conversation-id}/messages/{message-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteMessage()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMessage$Response(params: DeleteMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteMessage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteMessage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMessage(params: DeleteMessage$Params, context?: HttpContext): Observable<void> {
    return this.deleteMessage$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `editMessage()` */
  static readonly EditMessagePath = '/api/v1/conversations/{conversation-id}/messages/{message-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `editMessage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  editMessage$Response(params: EditMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageResponse>> {
    return editMessage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `editMessage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  editMessage(params: EditMessage$Params, context?: HttpContext): Observable<MessageResponse> {
    return this.editMessage$Response(params, context).pipe(
      map((r: StrictHttpResponse<MessageResponse>): MessageResponse => r.body)
    );
  }

}
