-- V1__init_conversations.sql
-- Replaces the original Chat(sender/recipient) design with a proper
-- Conversation + ConversationParticipant model (multi-party ready, per-user unread counters).

CREATE TABLE users (
    id                  VARCHAR(255) PRIMARY KEY,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    email               VARCHAR(255),
    last_seen           TIMESTAMP(6),
    created_date        TIMESTAMP(6) NOT NULL,
    last_modified_date  TIMESTAMP(6)
);

CREATE TABLE conversations (
    id                  UUID PRIMARY KEY,
    type                VARCHAR(20) NOT NULL,
    last_message_id     BIGINT,
    created_date        TIMESTAMP(6) NOT NULL,
    last_modified_date  TIMESTAMP(6)
);

CREATE TABLE conversation_participants (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id         UUID NOT NULL REFERENCES conversations(id),
    user_id                 VARCHAR(255) NOT NULL REFERENCES users(id),
    role                    VARCHAR(20) NOT NULL,
    joined_at               TIMESTAMP(6) NOT NULL,
    last_read_message_id    BIGINT,
    unread_count            INTEGER NOT NULL DEFAULT 0,
    created_date            TIMESTAMP(6) NOT NULL,
    last_modified_date      TIMESTAMP(6),
    CONSTRAINT uk_conv_participant UNIQUE (conversation_id, user_id)
);

CREATE TABLE messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id     UUID NOT NULL REFERENCES conversations(id),
    sender_id           VARCHAR(255) NOT NULL REFERENCES users(id),
    type                VARCHAR(20) NOT NULL,
    content             TEXT,
    status              VARCHAR(20) NOT NULL,
    created_date        TIMESTAMP(6) NOT NULL,
    last_modified_date  TIMESTAMP(6)
);

CREATE TABLE attachments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id          BIGINT NOT NULL REFERENCES messages(id),
    object_key          VARCHAR(512) NOT NULL,
    bucket              VARCHAR(255) NOT NULL,
    mime_type           VARCHAR(255) NOT NULL,
    size_bytes          BIGINT NOT NULL,
    width               INTEGER,
    height              INTEGER,
    duration_seconds    INTEGER,
    created_date        TIMESTAMP(6) NOT NULL,
    last_modified_date  TIMESTAMP(6)
);

-- Cursor-based pagination on messages (id DESC)
CREATE INDEX idx_messages_conversation_id ON messages (conversation_id);
CREATE INDEX idx_messages_conversation_id_id ON messages (conversation_id, id);

CREATE INDEX idx_conversation_participants_user_id ON conversation_participants (user_id);
CREATE INDEX idx_attachments_message_id ON attachments (message_id);

ALTER TABLE conversations
    ADD CONSTRAINT fk_conversations_last_message
        FOREIGN KEY (last_message_id) REFERENCES messages(id);

ALTER TABLE conversation_participants
    ADD CONSTRAINT fk_participants_last_read_message
        FOREIGN KEY (last_read_message_id) REFERENCES messages(id);
