CREATE TABLE reactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id     VARCHAR(255) NOT NULL REFERENCES users(id),
    emoji       VARCHAR(10) NOT NULL,
    created_date TIMESTAMP(6) NOT NULL,
    last_modified_date TIMESTAMP(6),
    CONSTRAINT uk_reaction_per_user_message UNIQUE (message_id, user_id)
);

CREATE INDEX idx_reactions_message_id ON reactions (message_id);
