-- V4__message_deletions.sql
-- Per-user "delete for me": a message stays fully visible to every participant
-- except those who explicitly removed it from their own view. Only the sender
-- can delete for everyone (messages.deleted_for_everyone).

CREATE TABLE message_deletions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id          BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id             VARCHAR(255) NOT NULL REFERENCES users(id),
    created_date        TIMESTAMP(6) NOT NULL,
    last_modified_date  TIMESTAMP(6),
    CONSTRAINT uk_message_deletion_per_user UNIQUE (message_id, user_id)
);

CREATE INDEX idx_message_deletions_message_id ON message_deletions (message_id);