-- V9__status.sql — ephemeral 24h statuses, separate from chat messages.
CREATE TABLE statuses (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type                VARCHAR(20) NOT NULL,
    content             TEXT,
    object_key          VARCHAR(512),
    bucket              VARCHAR(255),
    mime_type           VARCHAR(255),
    size_bytes          BIGINT,
    expires_at          TIMESTAMP(6) NOT NULL,
    created_date        TIMESTAMP(6) NOT NULL,
    last_modified_date  TIMESTAMP(6)
);

CREATE INDEX idx_statuses_user_expires ON statuses (user_id, expires_at);
CREATE INDEX idx_statuses_expires ON statuses (expires_at);
