/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AttachmentResponse {
  durationSeconds?: number;
  height?: number;
  id?: number;
  mimeType?: string;
  objectKey?: string;
  sizeBytes?: number;
  url?: string;
  width?: number;
}
