/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageResponse } from '../models/message-response';
export interface MessagePageResponse {
  hasMore?: boolean;
  messages?: Array<MessageResponse>;
  nextCursor?: number;
}
