/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateConversationRequest } from '../../models/create-conversation-request';
import { StringResponse } from '../../models/string-response';

export interface CreateConversation$Params {
      body: CreateConversationRequest
}

export function createConversation(http: HttpClient, rootUrl: string, params: CreateConversation$Params, context?: HttpContext): Observable<StrictHttpResponse<StringResponse>> {
  const rb = new RequestBuilder(rootUrl, createConversation.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StringResponse>;
    })
  );
}

createConversation.PATH = '/api/v1/conversations';
